name: toronto-shared-bike

services:
  fastapi:
    container_name: fastapi-container
    image: simonangelfong/toronto-shared-bike-fastapi-prebuilt:v1.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ORCLDB_HOST=oracle19c
      - ORCLDB_PORT=${ORCLDB_PORT}
      - ORCLDB_SERVICE=${ORCLDB_SERVICE}
      - ORCLDB_USER=${ORCLDB_USER}
      - ORCLDB_API_PWD=/run/secrets/orcl_api_pwd
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - public-net
      - private-net
    secrets:
      - orcl_api_pwd
    depends_on:
      oracle19c:
        condition: service_healthy

  oracle19c:
    container_name: database-container
    # image: simonangelfong/oracledb19c:1.0
    image: simonangelfong/toronto-shared-bike-db-prebuilt:year2019
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ORACLE_SID=${ORCLDB_SID} # sid, otherwise cannot login as sysdba
      - ORACLE_PWD=/run/secrets/orcl_sys_pwd
    volumes:
      - ./setup:/opt/oracle/scripts/setup # script to run after setup
      - ./startup:/opt/oracle/scripts/startup # script to run after startup
      - ../data:/tmp # source data
      - oracledata:/opt/oracle/oradata # persist data
    healthcheck:
      test:
        [
          "CMD",
          "sqlplus",
          "-S",
          "sys/${ORACLE_PWD}@${ORACLE_SID}",
          "as",
          "sysdba",
          "<<<",
          "exit",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5m
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 8g
        reservations:
          memory: 4g
    secrets:
      - orcl_sys_pwd
    networks:
      - private-net

volumes:
  oracledata:

networks:
  public-net:
    driver: bridge
  private-net:
    driver: bridge
    internal: true

secrets:
  orcl_api_pwd:
    file: ./secrets/orcl_api_pwd.txt
  orcl_sys_pwd:
    file: ./secrets/orcl_sys_pwd.txt
