SET SERVEROUTPUT ON;
ALTER SESSION SET CONTAINER=toronto_shared_bike;

-- Drop tbsp
DROP TABLESPACE fact_tbsp
INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

DROP TABLESPACE dim_tbsp
INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

DROP TABLESPACE index_tbsp
INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

DROP TABLESPACE staging_tbsp
INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

